name: Dump Wepage Collected Data

on:
  repository_dispatch:
    types: [dump_data]

jobs:
  dump_data_job:
    runs-on: ubuntu-latest
    steps:
      # name: Checkout repository
      #  uses: actions/checkout@v2

      - name: Dump Data
        run: |
          # Die Ã¼bergebenen Parameter aus dem JSON-Payload erhalten
          nickname=${{ github.event.client_payload.nickname }}
          email=${{ github.event.client_payload.email }}

          # Ergebnis ausgeben
          echo "Der Nutzer ${nickname}} hat die email ${email}"

